version: '3.1'

services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
            - '6001:6001'
            - '8025:8025'
            - '5173:5173'
            - '4000:4000'
        container_name: cogni-proxy
        restart: unless-stopped
        volumes:
            - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
            - '/etc/letsencrypt:/etc/letsencrypt'
        depends_on:
            - portal
            - emotion
            - phpmyadmin
            - mailhog
            - soketi
        networks:
            - public

    portal:
        build:
            dockerfile: docker/Dockerfile.local
            no_cache: true
            context: .
        container_name: cogni-portal
        volumes:
            - '.:/var/www'
            - 'avatars:/var/www/storage/avatars'
        expose:
            - 80
            - 5173
        restart: unless-stopped
        depends_on:
            - database
            - redis
            - soketi
            - mailhog
        networks:
            - public
            - private

    emotion:
        image: cognixrhealth/emotion-detection-api:latest
        expose:
            - 80
        container_name: cogni-emotion
        restart: unless-stopped
        networks:
            - public

    database:
        image: mariadb:10
        container_name: cogni-database
        expose:
            - 3306
        environment:
            MARIADB_ROOT_PASSWORD:
            MYSQL_ROOT_HOST: '%'
            MARIADB_DATABASE: cognimeet
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        volumes:
            - 'database:/var/lib/mysql'
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-p']
            retries: 3
            timeout: 5s
        networks:
            - private

    redis:
        image: 'redis:alpine'
        container_name: cogni-cache
        expose:
            - 6379
        volumes:
            - 'cache:/data'
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s
        networks:
            - private

    soketi:
        image: 'quay.io/soketi/soketi:1.4-16-debian'
        container_name: cogni-socket
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_ENABLED: '0'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DB_REDIS_HOST: redis
            SOKETI_DB_REDIS_PORT: '6379'
        expose:
            - 6001
        restart: unless-stopped
        depends_on:
            - redis
        networks:
            - public
            - private

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: cogni-phpmyadmin
        environment:
            PMA_HOST: database
            PMA_USER: root
        expose:
             - 4000
        restart: unless-stopped
        depends_on:
            - database
        networks:
            - public
            - private

    mailhog:
        image: 'mailhog/mailhog'
        container_name: cogni-mailing
        expose:
            - 1025
            - 8025
        restart: unless-stopped
        networks:
            - public

volumes:
    database:
    cache:
    avatars:

networks:
    public:
    private:
